/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xu83HGqWm",
    "aws_user_pools_web_client_id": "37pagnpl83pt17a74posg49s8u",
    "oauth": {
        "domain": "nlpjs.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin",
            "TrainingApp.admin"
        ],
        "redirectSignIn": "http://localhost:3000/auth.html/",
        "redirectSignOut": "http://localhost:3000/signout.html/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
