/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RKtnwv21w",
    "aws_user_pools_web_client_id": "2p768qd6rf881irm3hqil0bqd2",
    "oauth": {
        "domain": "nlpjs.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin",
            "TrainingApp.admin"
        ],
        "redirectSignIn": "http://localhost:3000/auth.html/",
        "redirectSignOut": "http://localhost:3000/signout.html/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
